import type { Metadata } from "next";
import { Suspense } from "react";

import "./globals.css";

import Loader from './(components)/Loader';
import Navbar from './(components)/Navbar';
import { OpenProvider } from "./(context)/Hamburger.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Suspense fallback={<Loader />} >
          <OpenProvider>
            <Navbar />
            {children}
          </OpenProvider>
        </Suspense>
      </body>
    </html>
  );
}
